### ISSUE TITLE
tick error

### ISSUE THREAD

**Issue by blackout314** [brunoscopelliti/marvin-demo#1]
/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:39
  goog.global.setTimeout(function() { throw exception; }, 0);

```
Error: Server terminated early with status 2
    at Error (<anonymous>)
    at /home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/remote/index.js:204:18
    at promise.ControlFlow.runInFrame_ (eval at <anonymous> (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:1857:20)
    at goog.defineClass.notify (eval at <anonymous> (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:2448:25)
    at promise.Promise.notify_ (eval at <anonymous> (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:564:12)
    at Array.forEach (native)
    at promise.Promise.notifyAll_ (eval at <anonymous> (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:553:15)
    at goog.async.run.processWorkQueue [as onTimeout] (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)
    at new Driver (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/chrome.js:783:36)
    at Builder.build (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/builder.js:454:14)
    at Object.<anonymous> (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/lib/webdriver/driver-session.js:28:10)
    at promise.ControlFlow.runInFrame_ (eval at <anonymous> (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:1857:20)
    at promise.ControlFlow.runEventLoop_ (eval at <anonymous> (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:1729:8)
    at eval (eval at <anonymous> (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:2043:12)
    at goog.async.run.processWorkQueue [as onTimeout] (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
From: Task: WebDriver.manage().timeouts().implicitlyWait(15000)
    at webdriver.WebDriver.schedule (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:362:15)
    at webdriver.WebDriver.Timeouts.implicitlyWait (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:1352:23)
    at Object.<anonymous> (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/lib/webdriver/driver-session.js:29:34)
    at promise.ControlFlow.runInFrame (eval at <anonymous> (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:1857:20)
    at promise.ControlFlow.runEventLoop_ (eval at <anonymous> (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:1729:8)
    at eval (eval at <anonymous> (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:2043:12)
    at goog.async.run.processWorkQueue [as _onTimeout] (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
From: Task: <anonymous>
    at Object.module.exports.execute (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/lib/webdriver/driver-session.js:39:44)
    at Object.module.exports.create (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/lib/webdriver/driver-session.js:24:17)
    at process.<anonymous> (/home/cdenaro/GIT/marvin-demo/node_modules/marvin-js/lib/test-runner/mocha.js:28:13)
    at process.emit (events.js:98:17)
    at handleMessage (child_process.js:322:10)
    at Pipe.channel.onread (child_process.js:349:11)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
 Use --force to continue.

```

**Comment by brunoscopelliti** [comment]
Hi @blackout314 ,

Can you give me please more info about your setup? OS? Nodejs version?
It works fine for me!

Thank you for reporting

**Comment by blackout314** [comment]
ubuntu 14.04
```
cdenaro@nb-cdenaro:~/GIT$ node -v
v0.10.40
```

**Comment by brunoscopelliti** [comment]
I am on the v0.12 branch...

```
node -v
> v0.12.3
```

Would you mind to try with the updated version... latest version is 0.12.7.
Off topic: so at the end you're not in the windows team ;)

**Comment by blackout314** [comment]
ooook, i try in node 0.12.x :-D :+1:
